name: user_repository
description: User repository
version: 1.0.1

publish_to: 'none'

#homepage:

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  pointycastle: ^3.4.0
  hex: ^0.2.0
  jwt_decoder: ^2.0.1
  dartz: ^0.10.0
  datasource_client:
    path: ../datasource_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
