name: ligas_futbol_flutter
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.57+47

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  # Service locator
  get_it: ^7.6.4
  # For state management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  # Allows value based equality for our classes
  equatable: ^2.0.5
  # Generates code for us by providing annotations we can use
  injectable: ^2.3.2
  # Allows converting json to dart class and back
  json_annotation: ^4.8.1
  # Code generator for data-classes
  freezed_annotation: ^2.4.1
  # Functional programming
  dartz: ^0.10.1
  # Form validation
  formz: ^0.4.1
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository
  datasource_client:
    path: packages/datasource_client
  here_repository:
    path: packages/here_repository
  notification_repository:
    path: packages/notification_repository
  #allows setting the web URL strategy
  url_strategy: ^0.2.0

  intl: ^0.18.1
  sms_autofill: ^2.3.0
  pin_code_fields: ^8.0.1
  splash_view: ^2.0.1
  font_awesome_flutter: ^10.6.0
  google_nav_bar: ^5.0.6
  carousel_slider: ^4.2.1
  scrollable_table_view: ^2.0.3
  dropdown_button2: ^1.8.9
  toggle_switch: ^2.1.0
  share_plus: ^7.2.1
  flutter_verification_code: ^1.1.7
  styled_widget: ^0.4.1
  flutter_map: ^3.1.0
  latlong2: 0.8.0
  url_launcher: ^6.2.2
  expansion_tile_card: ^3.0.0
  image_picker: ^1.0.4
  new_im_animations: ^0.1.1
  permission_handler: ^11.1.0
  location: ^5.0.3
  firebase_core: ^2.24.2
  flutter_local_notifications: ^16.2.0
  google_fonts: ^4.0.4
  flow_builder: ^0.0.10
  fl_chart: ^0.65.0
  loading_animation_widget: ^1.2.0+4
  animated_snack_bar: ^0.4.0
  flutter_image_compress: ^2.1.0
  image_cropper: ^4.0.0
  flutter_contacts: ^1.1.7+1
  top_snackbar_flutter: ^2.1.1
  extended_icon_button: ^1.0.0
  table_calendar: ^3.0.9
  time_pickerr: ^1.0.6
  #time picker scroll
  time_picker_sheet: ^0.0.2+1
  #Tutorial flutter
  tutorial_coach_mark: ^1.2.11
  geolocator: ^10.1.0
  group_radio_button: ^1.3.0
  dropdown_search: ^5.0.6
  empty_widget: ^0.0.3


  flutter_localizations:
    sdk: flutter
  firebase_performance: ^0.9.2+7
  #new_version_plus: ^0.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  injectable_generator:
  build_runner: ^2.4.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/