name: ligas_futbol_flutter
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.8.56+46

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Service locator
  get_it: ^7.2.0
  # For state management
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  # Allows value based equality for our classes
  equatable: ^2.0.3
  # Generates code for us by providing annotations we can use
  injectable: ^1.5.0
  # Allows converting json to dart class and back
  json_annotation: ^4.8.0
  # Code generator for data-classes
  freezed_annotation: ^2.2.0
  # Functional programming
  dartz: ^0.10.0
  # Form validation
  formz: ^0.4.0
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository
  datasource_client:
    path: packages/datasource_client
  here_repository:
    path: packages/here_repository
  notification_repository:
    path: packages/notification_repository
  #allows setting the web URL strategy
  url_strategy: ^0.2.0

  intl: ^0.18.0
  sms_autofill: ^2.2.0
  pin_code_fields: ^7.3.0
  splash_view: ^2.0.1
  font_awesome_flutter: ^10.2.1
  google_nav_bar: ^5.0.6
  carousel_slider: ^4.1.1
  scrollable_table_view: ^1.0.0
  dropdown_button2: ^1.8.9
  toggle_switch: ^2.0.1
  share_plus: ^5.0.0
  flutter_verification_code: ^1.1.6
  styled_widget: ^0.4.1
  flutter_map: ^3.1.0
  latlong2: 0.8.0
  url_launcher: ^6.1.5
  expansion_tile_card: ^3.0.0
  image_picker: ^0.8.4+10
  new_im_animations: ^0.1.1
  permission_handler: ^10.4.3
  location: 4.4.0
  firebase_core: ^2.17.0
  flutter_local_notifications: 9.7.1
  google_fonts: ^4.0.4
  flow_builder: ^0.0.6
  fl_chart: ^0.55.2
  loading_animation_widget: ^1.1.0+5
  animated_snack_bar: ^0.3.0
  flutter_image_compress: ^1.1.3
  image_cropper: ^3.0.1
  flutter_contacts: ^1.1.5+1
  top_snackbar_flutter: ^2.1.1
  extended_icon_button: ^1.0.0
  table_calendar: ^3.0.8
  time_pickerr: ^1.0.6
  #Tutorial flutter
  tutorial_coach_mark: ^1.2.8
  geolocator: ^9.0.2
  group_radio_button: ^1.3.0


  flutter_localizations:
    sdk: flutter
  firebase_performance: ^0.9.2+7
  new_version_plus: ^0.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator:
  build_runner: ^2.3.3
  freezed: ^2.3.3
  json_serializable: ^6.1.3
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/