name: notification_repository
description: Notification repository
version: 1.0.0

publish_to: 'none'

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  firebase_messaging: ^14.6.9
  rxdart: ^0.27.7
  datasource_client:
    path: ../datasource_client
  dartz: ^0.10.0
  #dartz: ^0.10.0
  #datasource_client:
  #  path: ../datasource_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
